[2023-07-28 16:03:50,981] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_test.get_data_mysql manual__2023-07-28T16:03:49.437051+00:00 [queued]>
[2023-07-28 16:03:50,990] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_test.get_data_mysql manual__2023-07-28T16:03:49.437051+00:00 [queued]>
[2023-07-28 16:03:50,990] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-07-28 16:03:50,990] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-07-28 16:03:50,990] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-07-28 16:03:51,004] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_data_mysql> on 2023-07-28 16:03:49.437051+00:00
[2023-07-28 16:03:51,009] {standard_task_runner.py:52} INFO - Started process 2399 to run task
[2023-07-28 16:03:51,012] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_test', 'get_data_***', 'manual__2023-07-28T16:03:49.437051+00:00', '--job-id', '292', '--raw', '--subdir', 'DAGS_FOLDER/simple_dag_connection.py', '--cfg-path', '/tmp/tmpv9x0q03o', '--error-file', '/tmp/tmp9qmk7xut']
[2023-07-28 16:03:51,013] {standard_task_runner.py:80} INFO - Job 292: Subtask get_data_***
[2023-07-28 16:03:51,063] {task_command.py:369} INFO - Running <TaskInstance: dag_test.get_data_mysql manual__2023-07-28T16:03:49.437051+00:00 [running]> on host ebe3e165ffca
[2023-07-28 16:03:51,141] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_test
AIRFLOW_CTX_TASK_ID=get_data_***
AIRFLOW_CTX_EXECUTION_DATE=2023-07-28T16:03:49.437051+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-28T16:03:49.437051+00:00
[2023-07-28 16:03:51,177] {logging_mixin.py:115} INFO - connect engine ***
[2023-07-28 16:03:51,177] {logging_mixin.py:115} INFO - connect engine ***
[2023-07-28 16:03:51,177] {python.py:173} INFO - Done. Returned value was: None
[2023-07-28 16:03:51,190] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_test, task_id=get_data_***, execution_date=20230728T160349, start_date=20230728T160350, end_date=20230728T160351
[2023-07-28 16:03:51,224] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-07-28 16:03:51,265] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
